# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d331c92c703e2d60a8bc83a1dbfd2c723622854f4fc1fc45bd05f0019c4fb7b62b305e317a00bbeb73516c4a4606b5e0714a050ce4184367bcb338df3a6eb9

test:
  secret_key_base: bce85fcb92ffeec4cf07c206b243710964fec63fc0fc3170263689774dbb244515c19dca86b2423dac55a70cf679ee36afe82b72b11522c2b72bcc115c305b63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
