# the association is created in the model not the controller
class SavedPreference < ActiveRecord::Base
  belongs_to :user  # user is the name of the model at the model level
  #serialize :location # this will turn the array generated by the checkboxes into a string which is the type of the locaiton attribute
  
end
